version: "3.9"

services:
  web:
    image: ghcr.io/4801f421/winclub_menu:latest
    container_name: winclub-menu-web
    ports:
      - "3010:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: winclub-menu-mongo
    env_file:
      - ./.env
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
      - winclub-mongo-data:/data/db
    restart: unless-stopped

volumes:
  winclub-mongo-data: